databases:
  - name: services
    plan: free
    databaseName: services
    user: mysite

services:
  - type: web
    plan: free
    name: BACKSERVICES
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn BACKSERVICES.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: services
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4